version: "3.8"
services:
  kong-database:
    image: postgres:10.5
    container_name: kong-database
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      KONG_PG_HOST: kong-database
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
  kong-prepare:
    image: kong:latest
    container_name: kong-prepare
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    command: "kong migrations bootstrap"
    networks:
      - kong-net
  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    networks:
      - kong-net    
  konga-prepare:
    container_name: konga-prepare
    image: pantsel/konga
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga_db"
    networks:
      - kong-net  
  konga:
    container_name: konga
    image: pantsel/konga
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: konga_db
      KONGA_HOOK_TIMEOUT: 120000
      NODE_ENV: production
    ports:
      - 1337:1337
    networks:
      - kong-net
networks:
  kong-net:
    external: true

